-- TRX ABANDONMENT MODULE

/*
2018/10/22
Business Rule Description:
Abandonment rate is defined as (reversed claims)/(paid + reversed claims)
Limited to the final claim of a patient's pharmacy encounter (CLAIM_STATUS = 'F')
All payer channels are included and are grouped as: Commercial, Medicare Part D, Medicaid (Managed & FFS), and Cash
Currently limited to Trulicity, but GLP-1 class level analysis may be added
Results are at the physician/quarter level, with payer channels pivoted to columns
Currently using calendar years and quarters; rolling time periods may be added
Results are also aggregated to the ZIP3 level or any geographic level for future use as a geographic rollup for low sample physicians
*/

/*
NOTES ON TABLES AND COLUMNS USED IN THIS MODULE

--MAIN FACT TABLE: DELIVERABLE_RX_FACT_A10211
	CONTAINS PRESCRIBER_ID, PATIENT_ID, AND ZIP CODE FOR THE PRESCRIBER
	CLAIM TYPE: CLAIM CAN BE REJECTED (RJ), REVERSED (RV), OR PAID (PD)
	NOTE: A REJECTED CLAIM IS NOT APPROVED BY THE PAYER, THEREFORE THESE CLAIMS ARE EXCLUDED FROM THIS ANALYSIS.
	REVERSED CLAIMS ARE APPROVED BY THE PAYER, BUT NOT PAID FOR BY THE PATIENT (ABANDONED)
	PAID CLAIMS ARE PAID FOR BY THE PATIENT (FILLED)

--DELIVERABLE_PLAN_A10211
	METHOD_OF_PAYMENT IS THE CHANNEL THROUGH WHICH THE PATIENT IS COVERED FOR A GIVEN CLAIM

--DELIVERABLE_PRODUCT_A10211
	BRAND_NAME IS THE DRUG NAME, IN THIS CASE TRULICITY
*/

--Sum filled and abandoned claims from fact table at physician/channel/quarter level
--DROP TABLE ABANDONMENT_PHYSICIAN_TRX
SELECT
	X.PRESCRIBER_ID, --PHYSICIAN LEVEL
	X.ZIP_CODE,
	P.BRAND_NAME, 	
	LEFT(X.SVC_DT,4) as F_YEAR,
	LEFT(X.SVC_DT,4)+'-Q'+CAST(DATEPART(QUARTER,X.SVC_DT) AS VARCHAR(1)) as F_QUARTER, -- WILL UPDATE TO A ROLLING QUARTER, PENDING INPUTS FROM LILLY
	CASE
		WHEN Z.METHOD_OF_PAYMENT in ('FFS MEDICAID','MGD MEDICAID')
			THEN 'MEDICAID'
		ELSE Z.METHOD_OF_PAYMENT
	END AS PAYER_CHANNEL,
	CASE																				
		WHEN X.CLAIM_TYPE = 'PD' 
			THEN 'FILLED'	
		WHEN X.CLAIM_TYPE = 'RV' 
			THEN 'ABANDONED'										
		ELSE NULL 
	END AS ABD_STATUS,
	COUNT(*) as CLAIM_COUNT
INTO ABANDONMENT_PHYSICIAN_TRX
FROM DELIVERABLE_RX_FACT_A10211 X
	JOIN DELIVERABLE_PLAN_A10211 Z 
		ON X.PLANTRAK_ID = Z.PLANTRAK_ID
	JOIN DELIVERABLE_PRODUCT_A10211 P 
		ON X.PRODUCT_ID = P.PRODUCT_ID
WHERE 
	X.LIFE_CYCLE_CLAIMS_YN = 'Y' 
	AND P.BRAND_NAME = 'TRULICITY' --LIMIT THE PULL TO TRULICITY CLAIMS ONLY AND WILL EXPAND TO GLP-1 AND BASAL CLASSES
	AND CLAIM_STATUS ='F'
	AND X.CLAIM_TYPE in ('PD','RV')
--TIME PERIOD WILL BE FURTHER REFINED ONCE CHANGING IT TO A ROLLING QUARTER
GROUP BY
	X.PRESCRIBER_ID, --PHYSICIAN LEVEL
	X.ZIP_CODE,
	P.BRAND_NAME, 	
	LEFT(X.SVC_DT,4),
	LEFT(X.SVC_DT,4)+'-Q'+CAST(DATEPART(QUARTER,X.SVC_DT) AS VARCHAR(1)),
	CASE
		WHEN Z.METHOD_OF_PAYMENT in ('FFS MEDICAID','MGD MEDICAID')
			THEN 'MEDICAID'
		ELSE Z.METHOD_OF_PAYMENT
	END,
	CASE																				
		WHEN X.CLAIM_TYPE = 'PD' 
			THEN 'FILLED'	
		WHEN X.CLAIM_TYPE = 'RV' 
			THEN 'ABANDONED'										
		ELSE NULL 
	END
GO			
--(467208 row(s) affected)

--qc
--SELECT TOP 100 * FROM ABANDONMENT_PHYSICIAN_TRX
select distinct METHOD_OF_PAYMENT FROM DELIVERABLE_PLAN_A10211

--Pivot channels to columns to get physician/quarter level results
--DROP TABLE ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_1
SELECT
	PRESCRIBER_ID,
	ZIP_CODE,
	BRAND_NAME,
	F_YEAR,
	F_QUARTER,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'COMMERCIAL' AND ABD_STATUS = 'FILLED' THEN CLAIM_COUNT
		ELSE 0
		END) AS COMMERCIAL_FILLED,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'COMMERCIAL' AND ABD_STATUS = 'ABANDONED' THEN CLAIM_COUNT
		ELSE 0
		END) AS COMMERCIAL_ABANDONED,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'MEDICARE PART D' AND ABD_STATUS = 'FILLED' THEN CLAIM_COUNT
		ELSE 0
		END) AS MEDICARE_FILLED,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'MEDICARE PART D' AND ABD_STATUS = 'ABANDONED' THEN CLAIM_COUNT
		ELSE 0
		END) AS MEDICARE_ABANDONED,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'MEDICAID' AND ABD_STATUS = 'FILLED' THEN CLAIM_COUNT
		ELSE 0
		END) AS MEDICAID_FILLED,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'MEDICAID' AND ABD_STATUS = 'ABANDONED' THEN CLAIM_COUNT
		ELSE 0
		END) AS MEDICAID_ABANDONED,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'CASH' AND ABD_STATUS = 'FILLED' THEN CLAIM_COUNT
		ELSE 0
		END) AS CASH_FILLED,
	SUM(
		CASE WHEN PAYER_CHANNEL = 'CASH' AND ABD_STATUS = 'ABANDONED' THEN CLAIM_COUNT
		ELSE 0
		END) AS CASH_ABANDONED
INTO ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_1
FROM ABANDONMENT_PHYSICIAN_TRX
GROUP BY
	PRESCRIBER_ID,
	ZIP_CODE,
	BRAND_NAME,
	F_YEAR,
	F_QUARTER
--(320828 row(s) affected)

--qc
--SELECT TOP 300 * FROM ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_1 ORDER BY PRESCRIBER_ID
--SELECT TOP 300 * FROM ABANDONMENT_PHYSICIAN_TRX ORDER BY PRESCRIBER_ID

--Adding in abandonment rate calculations at physician/channel/quarter level
--DROP TABLE ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_2
SELECT
	PRESCRIBER_ID,
	ZIP_CODE,
	BRAND_NAME,
	F_YEAR,
	F_QUARTER,
	COMMERCIAL_FILLED,
	COMMERCIAL_ABANDONED,
	(CAST(COMMERCIAL_ABANDONED AS FLOAT)/NULLIF(CAST(COMMERCIAL_ABANDONED + COMMERCIAL_FILLED AS FLOAT),0)) as COMMERCIAL_ABD_RATE,
	(COMMERCIAL_FILLED + COMMERCIAL_ABANDONED) as COMMERCIAL_SAMPLE,
	MEDICARE_FILLED,
	MEDICARE_ABANDONED,
	(CAST(MEDICARE_ABANDONED AS FLOAT)/NULLIF(CAST(MEDICARE_ABANDONED + MEDICARE_FILLED AS FLOAT),0)) as MEDICARE_ABD_RATE,
	(MEDICARE_FILLED + MEDICARE_ABANDONED) as MEDICARE_SAMPLE,
	MEDICAID_FILLED,
	MEDICAID_ABANDONED,
	(CAST(MEDICAID_ABANDONED AS FLOAT)/NULLIF(CAST(MEDICAID_ABANDONED + MEDICAID_FILLED AS FLOAT),0)) as MEDICAID_ABD_RATE,
	(MEDICAID_FILLED + MEDICAID_ABANDONED) as MEDICAID_SAMPLE,
	CASH_FILLED,
	CASH_ABANDONED,
	(CAST(CASH_ABANDONED AS FLOAT)/NULLIF(CAST(CASH_ABANDONED + CASH_FILLED AS FLOAT),0)) as CASH_ABD_RATE,
	(CASH_FILLED + CASH_ABANDONED) as CASH_SAMPLE,
	(COMMERCIAL_FILLED + COMMERCIAL_ABANDONED + MEDICARE_FILLED + MEDICARE_ABANDONED + MEDICAID_FILLED + MEDICAID_ABANDONED + CASH_FILLED + CASH_ABANDONED) as TOTAL_SAMPLE
INTO ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_2
FROM ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_1
WHERE
	PRESCRIBER_ID IS NOT NULL
--(320817 row(s) affected)

--qc
--SELECT TOP 100 * FROM ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_2

--Creating alternate table at the ZIP-3 level
--OTHER GEOGRAPHIC LEVEL ALTERNATIVE CAN ALSO BE CONSIDERED
--DROP TABLE ABANDONMENT_PHYSICIAN_TRX_ZIP3_CHANNEL
SELECT
	LEFT(ZIP_CODE,3) as ZIP3,
	BRAND_NAME,
	F_YEAR,
	F_QUARTER,
	SUM(COMMERCIAL_FILLED) as COMMERICAL_FILLED,
	SUM(COMMERCIAL_ABANDONED) as COMMERCIAL_ABANDONED,
	(CAST(SUM(COMMERCIAL_ABANDONED) AS FLOAT)/NULLIF(CAST(SUM(COMMERCIAL_ABANDONED) + SUM(COMMERCIAL_FILLED) AS FLOAT),0)) as COMMERCIAL_ABD_RATE,
	(SUM(COMMERCIAL_FILLED) + SUM(COMMERCIAL_ABANDONED)) as COMMERCIAL_SAMPLE,
	SUM(MEDICARE_FILLED) as MEDICARE_FILLED,
	SUM(MEDICARE_ABANDONED) as MEDICARE_ABANDONED,
	(CAST(SUM(MEDICARE_ABANDONED) AS FLOAT)/NULLIF(CAST(SUM(MEDICARE_ABANDONED) + SUM(MEDICARE_FILLED) AS FLOAT),0)) as MEDICARE_ABD_RATE,
	(SUM(MEDICARE_FILLED) + SUM(MEDICARE_ABANDONED)) as MEDICARE_SAMPLE,
	SUM(MEDICAID_FILLED) as MEDICAID_FILLED,
	SUM(MEDICAID_ABANDONED) as MEDICAID_ABANDONED,
	(CAST(SUM(MEDICAID_ABANDONED) AS FLOAT)/NULLIF(CAST(SUM(MEDICAID_ABANDONED) + SUM(MEDICAID_FILLED) AS FLOAT),0)) as MEDICAID_ABD_RATE,
	(SUM(MEDICAID_FILLED) + SUM(MEDICAID_ABANDONED)) as MEDICAID_SAMPLE,
	SUM(CASH_FILLED) as CASH_FILLED,
	SUM(CASH_ABANDONED) as CASH_ABANDONED,
	(CAST(SUM(CASH_ABANDONED) AS FLOAT)/NULLIF(CAST(SUM(CASH_ABANDONED) + SUM(CASH_FILLED) AS FLOAT),0)) as CASH_ABD_RATE,
	(SUM(CASH_FILLED) + SUM(CASH_ABANDONED)) as CASH_SAMPLE,
	(SUM(COMMERCIAL_FILLED) + SUM(COMMERCIAL_ABANDONED) + SUM(MEDICARE_FILLED) + SUM(MEDICARE_ABANDONED) + SUM(MEDICAID_FILLED) + SUM(MEDICAID_ABANDONED) + SUM(CASH_FILLED) + SUM(CASH_ABANDONED)) as TOTAL_SAMPLE
INTO ABANDONMENT_PHYSICIAN_TRX_ZIP3_CHANNEL
FROM ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_1
WHERE
	ZIP_CODE IS NOT NULL
GROUP BY
	LEFT(ZIP_CODE,3),
	BRAND_NAME,
	F_YEAR,
	F_QUARTER
--(9540 row(s) affected)

--The two output tables from this module:
SELECT TOP 100 * FROM ABANDONMENT_PHYSICIAN_TRX_CHANNEL_PIVOT_2
SELECT TOP 100 * FROM ABANDONMENT_PHYSICIAN_TRX_ZIP3_CHANNEL